- README.md
@bkueng I could not use pip3 for sqlite3 but it worked with apt-get, and I added that you have to sync submodules
> Updated install docs

- README.md
- data/.gitignore
- plot_app/config.py
- plot_app/configured_plots.py
- plot_app/plotting.py
- plot_app/static/css/main.css
- plot_app/static/js/main.js
- plot_app/templates/header.html
- plot_app/templates/index.html
- setup_db.py
- tornado_handlers.py
Switch to KML-based Google maps, because the bokeh version has some issues (initialization, zooming).
Added benefit: download option for KML.
Drawback: the KML map does not work locally, because Google requires the link to be publicly available.
Once bokeh has better support, we can switch back.
Fixes #5 and #12
> Switch to Google Maps KML layer

- browse.html
- delete_db_entry.py
- edit.html
- plot_app/config.py
- plot_app/helper.py
- plot_app/static/css/main.css
- send_email.py
- serve.py
- setup_db.py
- tornado_handlers.py
It works as following:
- a random Token is generated on file upload and stored in the DB
- the notification email contains a delete link, including the token
- clicking the link requires first to confirm the removal of the file
- upon confirmation, token will be compared and the entry removed if
successful
Fixes #10
> Add ability to delete log files

- backup_db.py
- plot_app/configured_plots.py
- plot_app/db_entry.py
- plot_app/helper.py
- plot_app/main.py
- plot_app/templates/upload.html
- pylintrc
- send_email.py
- setup_db.py
- tornado_handlers.py
This shows the vehicle uuid and total flight time on the plot page.
In addition an uploader can provide a vehicle name, which will be matched against the uuid and shown as well. If no name is provided and a name already exists, the existing one will be used. If a name is provided, it will overwrite any existing name for that uuid.
> Vehicle UUID and flight time

- plot_app/configured_plots.py
- plot_app/plotting.py
Fixes https://github.com/PX4/flight_review/issues/43
> plots: mark NaN values using a vertical dotted line with label 'NaN'

- plot_app/configured_plots.py
- plot_app/helper.py
- plot_app/plotting.py
- plot_app/static/css/main.css
- plot_app/templates/main.js
- pylintrc
Showing some key numbers:
@MaEtUgR is this close to what you had in mind?
> Plots: add a text column on the top right

- plot_app/configured_plots.py
- plot_app/plotting.py
- this PR changes the title of the spectrogram plot to add the unit (dB) for the power spectral density
> add measurement unit to spectrogram title

- plot_app/configured_plots.py
@dagar this is how it looks like:
Fixes #70
> Watchdog plot: separate bits and plot only the non-zero bits

- tornado_handlers.py
- this pr fixes an index overflow bug on the browse page
> browse page: fix db length index overflow

- plot_app/static/js/radio_controller.js
- plot_app/templates/3d.html
- tornado_handlers/three_d.py
> 3D view: make manual control setpoint optional

- .travis.yml
- plot_app/configured_plots.py
- plot_app/helper.py
It can help with vehicle tuning
> Add integral to rates plot

- plot_app/configured_plots.py
- plot_app/helper.py
- testing_notebook.ipynb
Firmware PR: https://github.com/PX4/Firmware/pull/8466
> plots: update mag & baro alt to new topics & keep compatibility with old logs

- download_logs.py
This pull request extends the `download_logs.py` script by an additional `--uuid` argument for filtering the database by vehicle UUID before downloading. 
This pull request also improves the `help` description of various other arguments.
> download logs filtered by vehicle uuid

- plot_app/config_tables.py
This pull requests adds a new precision land flight mode row to the flight modes table.
> integrate precision land flight mode

- plot_app/templates/browse.html
- tornado_handlers/browse.py
This was requested in #121 
Additionally, this also adds the search to the browse url for better shareability.
> Add UUID and software version to the public logs search

- plot_app/configured_plots.py
This PR syncs with and addresses the changes done in https://github.com/PX4/Firmware/pull/10077. @bkueng can you please validate it? Thanks
> configure_plots: update system_power fields naming

- download_logs.py
Added some new features to the download_logs.py script:
* Allow specifying multiple uuids
* Add a flag to filter by log_id
* Make the download more resilient by retrying downloads
> Improve the download_logs.py script

- plot_app/configured_plots.py
With Flight Tasks this is now more extensively used (and the yaw setpoint is just set to the current yaw).
> Yaw plot: add yaw feed-forward setpoint

- README.md
Add instructions about how to install the dependencies on macOS.
> Installation instructions for macOS

- config_default.ini
- plot_app/config.py
- plot_app/configured_plots.py
- plot_app/main.py
- plot_app/static/css/main.css
- plot_app/templates/footer.html
- plot_app/templates/header.html
- plot_app/templates/index.html
replace leaflet plug-in to replace google map
> Pr leaflet

- plot_app/db_entry.py
- plot_app/templates/browse.html
- setup_db.py
- tornado_handlers/browse.py
- tornado_handlers/common.py
There is an implementation of an other usefull function on browse page.
Sorting is done by sqlite queries, so results can be sorted only by colums which are saved in DB. We added a new colum with Datetime of start of flight.
But there is an Python error -> I really dont know, how to call Super class init metod coreclty with multiple parents..
> Browse Page - Sort

- plot_app/db_entry.py
- tornado_handlers/db_info_json.py
this pull request exposes the information about the upload source in the db info json API.
> add source information to db info json

- plot_app/configured_plots.py
Shows the output from https://github.com/PX4/Firmware/pull/11792.
> plots page: add console output ('boot_console_output' messages)

- Dockerfile
Usage instructions in base of file - once running access via web-browser using docker instance IP.
> Dockerfile that will run PX4 Flight Review

- Dockerfile
Updated so that changes to the locally cloned repo can be run by the Dockerfile, for those looking for the master version either do a refresh checkout of the project or stash any changes before running the docker build command. (#166)
> Use local project source in docker container

- plot_app/configured_plots.py
- plot_app/helper.py
Hi all,
I thing i can be usefull to have an temperature graph in outputs. What do you mean about it?
(now it supports sensors temperatures, in a future we may add separate temperature sensor into PX4 Firmware.)
Thank for your replies
> Add graph of temperatures from various sensors.

- plot_app/configured_plots.py
- plot_app/helper.py
- plot_app/main.py
- plot_app/pid_analysis_plots.py
- plot_app/plotting.py
- pylintrc
> Plot highrate accel/gyro fifo data

- plot_app/configured_plots.py
- plot_app/helper.py
add airspeed_validated if airspeed is not confidence
> add airspeed_validated

- plot_app/configured_plots.py
> fix airspeed plot issue

- plot_app/configured_plots.py
This fixes a typo preventing the distance sensor plot to appear.
> fix: typo in variance topic for distance sensor plot

- plot_app/configured_plots.py
- plot_app/helper.py
From PX4/PX4-Autopilot#16270 and PX4/PX4-Autopilot#16557
> uorb topic updates (manual_control_switches & system_power)

- plot_app/config.py
- plot_app/configured_plots.py
- plot_app/plotted_tables.py
- requirements.txt
From https://github.com/PX4/PX4-user_guide/pull/1103
- the list still contains all params different from system-default
- params different from airframe default are marked red
> parameters: show airframe default parameter values 

- app/plot_app/configured_plots.py
> Add VIO latency plot

- app/plot_app/configured_plots.py
- app/plot_app/plotting.py
- run_pylint.sh
- add angular velocity and acceleration FFTs
- plot IMU_GYRO_NF_FREQ if set
- use timestamp_sample if available
- remove hard coded y range and amplitude scaling
- use timestamp_sample if available
- allow zooming in y
> add angular velocity and angular acceleration FFTs

- .gitignore
- .gitmodules
- README.md
- app/config_default.ini
- app/plot_app/config.py
- app/plot_app/configured_plots.py
- app/plot_app/helper.py
- app/plot_app/plotted_tables.py
- run_pylint.sh
From https://github.com/PX4/PX4-Autopilot/pull/17479
> parse & show events

- app/plot_app/configured_plots.py
This adds 'temperature' from 'battery_status' to the Temperature plot.
> Add battery temperature plot

- app/download_logs.py
- app/plot_app/config.py
- app/plot_app/events.py
- app/plot_app/helper.py
- app/plot_app/plotted_tables.py
- app/pylintrc
From https://github.com/PX4/PX4-Autopilot/pull/20332
> events: extract metadata from log & cache the files

- app/plot_app/configured_plots.py
- app/plot_app/helper.py
From https://github.com/PX4/PX4-Autopilot/pull/20401
> plots: add failsafe flags & remove RC quality

- app/plot_app/configured_plots.py
- app/plot_app/templates/3d.html
- app/pylintrc
- app/tornado_handlers/three_d.py
Update for https://github.com/PX4/PX4-Autopilot/pull/15949
@MaEtUgR
> Manual control setpoint update

- app/plot_app/configured_plots.py
It works without the try except statements, but throws errors when the data doesn't exist in a particular log.
```
<class 'IndexError'> (vehicle_local_position_groundtruth): list index out of range
<class 'IndexError'> (vehicle_attitude_groundtruth): list index out of range
<class 'IndexError'> (vehicle_angular_velocity_groundtruth): list index out of range
<class 'IndexError'> (vehicle_attitude_groundtruth): list index out of range
<class 'IndexError'> (vehicle_angular_velocity_groundtruth): list index out of range
<class 'IndexError'> (vehicle_attitude_groundtruth): list index out of range
<class 'IndexError'> (vehicle_angular_velocity_groundtruth): list index out of range
<class 'IndexError'> (tecs_status): list index out of range
<class 'IndexError'> (rc_channels): list index out of …
```
> Remove except pass

- app/plot_app/configured_plots.py
I tried to filter the dist_bottom values by the valid flag, but I couldn't figure out how to do it cleanly.
> Add dist_bottom to distance plot

- app/plot_app/configured_plots.py
System power graph is broken with the new battery_status message where filtered voltage is removed.
This PR with the new battery_status message
This PR with a log with the old battery_status message.
> Fix power graph. Add open circuit voltage and internal resistance.

- app/plot_app/templates/browse.html
- app/plot_app/templates/upload.html
This got raised here: https://discuss.px4.io/t/license-for-the-dataset
> public logs: clarify data license (CC-BY)

- app/plot_app/templates/3d.html
Otherwise roll/pitch is incorrect
Follow-up to https://github.com/PX4/flight_review/pull/301
> fix 3D: apply model rotation before applying the vehicle attitude

- app/tornado_handlers/three_d.py
This happend here: https://github.com/PX4/flight_review/issues/308, which is a SITL log.
Fixes https://github.com/PX4/flight_review/issues/308
> 3d: handle the case if 'time_utc_usec' is 0
