PX4/flight_review

README.md, plot_app/configured_plots.py, plot_app/main.py, plot_app/static/css/main.css, setup_db.py, tornado_handlers.py, upload.html
This adds a separate tab on the upload page, for flight testing with additional fields like weather & flight rating. It looks like this:
@dogmaphobic: can you please extend QGC to add these fields?
@sanderux @LorenzMeier @kd0aij Any suggestions for additional fields/changes?
=> Extend for flight testing uploads

config_default.ini, plot_app/config.py, plot_app/configured_plots.py, plot_app/helper.py, plot_app/templates/header.html, tornado_handlers.py
This adds a table showing the non-default parameters. The default parameters are obtained from the S3 parameters.xml based on master.
Additionally it adds a download option for the non-default params.
@MaEtUgR
=> Show non-default params in a table

config_default.ini, plot_app/config.py, plot_app/configured_plots.py, plot_app/db_entry.py, plot_app/main.py, plot_app/plotting.py, plot_app/static/css/main.css, plot_app/statistics_plots.py, plot_app/templates/footer.html, plot_app/templates/header.html, plot_app/templates/index.html, plot_app/templates/main.js, prune_old_logs.py, pylintrc, serve.py, setup_db.py, tornado_handlers.py
Looks like this:
There's also a mouse-over hover tool showing more details:
I can add some more, like a pie chart for the rating, but in general I'd like to keep a small set of meaningful plots, rather than many that are not that useful.
@dagar the airframes xml from http://px4-travis.s3.amazonaws.com/Firmware/master/airframes.xml does not contain the Intel Aero - probably because it's excluded on some boards. However running `make px4_metadata` in FW does contain it. Am I using the wrong URL?
@LorenzMeier is this about what you had in mind for https://github.com/PX4/flight_review/issues/9 and #7?
=> Add Statistics Page

README.md, plot_app/configured_plots.py, plot_app/main.py, plot_app/statistics_plots.py
- Do not show CI logs, only show the total number instead, so that the private logs graph is better visible (the CI graph is not really interesting, as it's just linearly increasing).
- Add plot: number of flights per board
- show innovation check flags in estimator watchdog
- plot ekf2 time slip
@priseborough This reveals there's a time slip of 20ms every time a parameter gets changed. Do you think that's an issue? Also the time continuously slightly increases. Is it due to floating point inaccuracies or is some scheduling overhead not taken into account?
Fixes https://github.com/PX4/flight_review/issues/42 #44
=> Stats page updates

plot_app/configured_plots.py
Hardfaults are shown at the top so they cannot be overlooked:
Perf & top data is at the botton using an expand button:
=> Show hardfaults, perf & top data

tornado_handlers.py
The content type was `text/html`, but should be `application/json`.
=> Fix /dbinfo Content-Type

data/.gitignore, download_logs.py
As is, the `download_logs.py` script fails due to a syntax error:
```bash
$ python download_logs.py
File "download_logs.py", line 35
if args.print:
^
SyntaxError: invalid syntax
```
This is now fixed without changing the API.
Also changed the default URLs to point to HTTPS instead to avoid relying on the server-side redirect for security. 
Finally, downloaded logs are no longer tracked, and this script won't fail if the intermediary directories in download path specified don't exist yet.
=> download_logs: fix script syntax error and default to HTTPS

plot_app/statistics_plots.py
For some reason, without this change I get this error when visiting the `/stats` page:
```bash
File "statistics_plots.py", line 510, in _plot_public_data_statistics:
area.legend[0].items.reverse() Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/bokeh/application/handlers/code_runner.py", line 81, in run
exec(self._code, module.__dict__)
File "/home/robotics/flight_review/plot_app/main.py", line 65, in <module>
p = statistics.plot_public_flight_mode_statistics()
File "/home/robotics/flight_review/plot_app/statistics_plots.py", line 397, in plot_public_flight_mode_statistics
self._all_flight_modes, 'flight_mode_durations', 'Flight Mode', label_callback)
File "/home/robotics/flight_review/plot_app/statistics_plots.py", line 510, in _plot_public_data_statistics …
```
=> statistics page: fix IndexError

README.md, plot_app/plotted_tables.py, plot_app/plotting.py, plot_app/templates/main.js, serve.py
This includes the following breaking changes:
- rename server args from tornado_server_kwargs to http_server_kwargs
And required fixes/updates:
- GMapPlot requires Range1d not DataRange1d
- param changes and vtol mode labels were offset in y-direction
- the Logging Start did not show up anymore. This changes the implementation
=> Upgrade to bokeh 0.12.11

plot_app/configured_plots.py, plot_app/plotting.py
In case of a slow setpoint updates, rendering a horizontal line is the
correct thing to do, because the controller will keep the setpoint.
However this does not entirely hold if setpoints are logged with lower
rate than what the system actually publishes and uses.
Before:
This PR:
(Note: this depends on #73)
=> plots: use step lines for attitude, rates & position setpoint graphs

plot_app/configured_plots.py, plot_app/plotting.py
- currently on certain (low quality?) screens, some of the flight mode
colors are hard to distinguish
- all the Auto modes had only a single color, i.e. it was not possible to
distinguish between Mission, RTL or Land.
Disadvantage: for certain logs, the plots start to look overloaded.
Examples:
Extreme case:
=> plots: show flight mode labels when hovering over the plot

plot_app/plotting.py
Spectrogram plots are uninformative and possibly confusing if the sampling rate of the raw acceleration data is low (see issue #75 ). This pull requests removes the spectrogram plot from the plotting page if the raw acceleration data is sampled below 100Hz.
- this pull request resolves issue #75 
- the spectrogram plot is removed from the plotting page by setting its _had_error flag
=> plot: only plot spectrogram if sampling frequency is higher than 100 Hz

plot_app/plotted_tables.py, plot_app/templates/main.js
@tubeme this correctly shows now 7:46 for the first log in https://github.com/PX4/Firmware/issues/8654:
Does that work for you?
Fixes: https://github.com/PX4/flight_review/issues/81
=> add tooltip to display time with timezone from log

plot_app/templates/browse.html
This fixes the following little rendering issue when searching logs. 
Might not be the best way to fix the issue, especially if you plan on using translations in the future. Other option would be to just set this to `""` or to make the browsing page the same width as the table. I like the latter best.
=> Fix search filtered text overflow

config_tables.py, download_logs.py, plot_app/config_tables.py, plot_app/helper.py
This pull request extends the download_logs script by command line arguments for filtering the database before downloading files.
- new arguments are added for filtering by mav type, flight modes, error labels and rating
- the flight mode and error label tables are moved from helper.py to a separate file config_tables.py
- The filters modify the db_entries_list to only download the types specified
- the list order is reversed to first download the newest data
=> add meta data filter options to downloading logs script

plot_app/configured_plots.py, plot_app/plotting.py
Should be useful for filter tuning and noise analysis. Requires high rate logging to be enabled in order for the plot to show up.
Example with different d-term cutoff frequencies:
d-term cutoff = 50:
d-term cutoff = 70: noise a bit increased, but still flies well:
d-term cutoff = 80: noticeable more noise, affecting flight performance:
Here's another interesting example:
Decreasing the d-term cutoff lead to an increase of the lower frequencies. I think it's because the D gain is a bit too high together with increased latency of the D-term signal.
@RomanBapst @MaEtUgR
=> Add actuator controls FFT plot

plot_app/configured_plots.py, plot_app/helper.py
Pretends to sync with https://github.com/PX4/Firmware/pull/9301 by replacing `vehicle_vision_position` and `vehicle_vision_attitude` with `vehicle_visual_odometry`, and `vehicle_local_position_groundtruth` and `vehicle_attitude_groundtruth` with `vehicle_groundtruth`.
=> plot_app: replace vision and ground truth topic plots

.travis.yml, README.md, plot_app/configured_plots.py, plot_app/plotting.py
scipy.fft becomes slow for input lengths that factorize into large primes. It runs with O(N^2) for prime lengths.
In some cases the page loading timed out because of this (FFT plots are only shown for logs with the high-rate logging profile active).
=> fix FFT performance: use fftw instead of scipy.fft

download_logs.py, tornado_handlers/db_info_json.py
this pr adds new fields (vehicle name, airframe name, airframe type) to the db entries list generated by the dbinfo api and adds these fields as filters for the download_logs script. 
- db_info_json: extract the vehicle name from the vehicles db and
generate the aiframe name and type; store them in json dictionary
returned by the dbinfo request
- download_logs: enable filtering by vehicle-name, airframe-name,
and airframe-type
=> dbinfo api: add vehicle name, airframe name & type to list returned from get request

tornado_handlers/db_info_json.py
this pr does a quick bugfix for a problem that hasn't been accounted for: `get_airframe_data` returning `None`
=> bugfix dbinfo api: account for airframe data being None

plot_app/configured_plots.py
According to @RomanBapst NaN attitude setpoints are valid for fixed-wing.
Example log: https://logs.px4.io/plot_app?log=ba165f7d-113d-4c5d-b479-1fcf21e99175
=> attitude plots: don't mark NaNs in the setpoint for fixed-wing

plot_app/configured_plots.py, plot_app/helper.py
#111 changes were meant to address PX4/Firmware#9301, which was replaced by PX4/Firmware#9895. This is rollback  to #111 to the have the correct groundtruth topics plotted.
=> Fix: Rename groundtruth topics

plot_app/configured_plots.py
Attitude plots (Roll Angle, Pitch Angle, Yaw Angle) are wrapped from -180° to 180°.
This causes poor plots, with weird "jumps", when the drone passes the 180° threshold, e.g., by oscillating in yaw around 180°:
By using the [numpy.unwrap()](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.unwrap.html) method, we can avoid those jumps and obtain a more continuous graph. The following example is the same plot as before, with the patch applied:
=> More readable angular plots with np.unwrap()

plot_app/configured_plots.py
This reverts commit 1a8900658168e79ce97d8cfbbd6d4025977862ef (https://github.com/PX4/flight_review/pull/141).
Problems:
- the angle can drift off by an arbitrary amount, especially noticeable for fixed-wings
- when switching to Acro, the angles can diverge from the setpoint
@pietrodn fyi
=> Revert "More readable angular plots with np.unwrap()"

plot_app/statistics_plots.py, tornado_handlers/browse.py
this pull request removes CI logs from the logs list in the browse page. with this pr PX4 Firmware CI logs may be uploaded as public without cluttering the flight log list.
=> remove CI logs from logs list in browse page

testing_notebook.ipynb
=> fixed reference to scipy.signal.spectrogram

plot_app/configured_plots.py, plot_app/plotting.py
Since EKF2 already provides a metric, we can just plot it. The last one based on accel is the most useful.
Examples:
The background color is an indicator for how good it is: preferably everything should be below 0.02. I tested this on a bunch of logs and the levels seem reasonable, but can be adjusted if needed.
The levels are also in agreement with the thresholds of the [ekf analysis tools](https://github.com/PX4/Firmware/tree/master/Tools/ecl_ekf).
It can be extended to do threshold checking and show warnings if thresholds are exceeded.
=> Vibration metrics plot

download_logs.py
This pull request adds two new filters to the download_logs script:
- source: filter the data-base entries by source type; `CI` and `webui` are the two options currently available
- git-hash: filter the data-base entries by PX4 software version (git-hash)
The two filters can be combined to download all logs created by PX4 CI for a particular software version:
```
python download_logs.py --source CI --git-hash PX4_SOFTWARE_GIT_HASH
```
=> add download filters for source type and git-hash

requirements.txt
Scipy version 1.4.x breaks the fft import in plotting.py for the wrapper pyfftw.
scipy.fftpack has been deprecated and is treated as legacy. Until a permanent change, this is a good temporary fix.
=> scipy>1.3.3 breaks the fft import

plot_app/configured_plots.py
-  since https://github.com/PX4/PX4-Autopilot/pull/16585, tecs_status.airspeed_sp got renamed to tecs_status.true_airspeed_sp
- EAS got renames to CAS --> I think though that it anyway is more useful to display TAS (true airspeed) in the Airspeed plot, as that's the one you can compare to groundspeed
=> Airspeed plot: display TAS instead of EAS and adapt to latest px4 conventions

plot_app/configured_plots.py
Currently when flying a vehicle that has an AUX mixer + also has UAVCAN ESCs the motors for the plots will not be plotted as they fall into `actuator_outputs.02`. This fixes that. It also removes `actuator_outputs.00` when this one is empty (which happens in the aforementioned case).
Current:
Fixed:
This is with a log from PX4 ~V1.10. Right now it's not really easy to reproduce this as there's an issue on PX4 with logging and `actuator_outputs.02`. Issue: https://github.com/PX4/PX4-Autopilot/issues/16414
Still to be done, The way that the plot titles are done is not right for these edge cases. If there's only UAVCAN the main outputs will go on AUX I believe, But this could be done in a separate PR.
Signed-off-by: Ricardo Marques <marques.ricardo17@gmail.com>
=> Add plot for third instance of actuator_outputs.

docker/docker-compose.yml
This commit adds automatic building of the px4flightreview image
to the docker-compose configuration. Additionally, it fixes a couple of
issues with the docker-compose configuration so the application starts
properly.
=> Add build section to docker-compose config, + minor changes

app/plot_app/configured_plots.py, app/plot_app/vtol_tailsitter.py
Hi, 
I have added some logic to do orientation conversion on attitude for tailsitters in fixed wing mode. Before this logic, tailsitters would appear very unable to track attitude trajectories in fixed wing mode. Now flight review can correctly display the tailsitter attitudes. See attached images for before and after.
=> Tailsitter attitude correction

app/requirements.txt
I noticed that when executing `pip install -r requirements.txt`, my Scipy 1.9.3 package got downgraded, due to hard constraint in the requirements file. This doesn't seem necessary since Scipy isn't such a crucial package in general as mentioned here: https://github.com/PX4/flight_review/issues/233#issuecomment-1089857342
Remove hard constraint on SciPy version, and accept install any version over 1.8.1 (and don't downgrade system package if already installed and is version higher than 1.8.1)
=> Accept any scipy version over 1.8.1

README.md, app/plot_app/configured_plots.py
The current vibration color thresholds are a couple of orders of magnitudes off from what the expected values are in PX4 now. 
I set them into the expected range but guessed at the specific values. We will need to determine the actual green, yellow, and red ranges.
The land detector uses these values to detect the last movement.
```
static constexpr float GYRO_VIBE_METRIC_MAX = 0.02f; // gyro_vibration_metric * dt * 4.0e4f > is_moving_scaler)
static constexpr float ACCEL_VIBE_METRIC_MAX = 1.2f; // accel_vibration_metric * dt * 2.1e2f > is_moving_scaler
if ((imu_status.gyro_vibration_metric > GYRO_VIBE_METRIC_MAX)
|| (imu_status.accel_vibration_metric > ACCEL_VIBE_METRIC_MAX)) {
_time_last_move_detect_us = imu_status.timestamp;
}
```
=> Update vibration metric color thresholds

app/plot_app/configured_plots.py
Show up to 4 IMUs. Usually 2-3 internal and possibly 1 external IMU.
Change the color thresholds to be gravity and 1/2 gravity.
=> Plot up to 4 imu vibration metrics. Update color thresholds

app/plot_app/plotting.py
timestamp_sample exists in the original dataset and is used by the spectrogram plotter; it needs to be fill correctly to have the right dimension
Before:
This PR:
=> Fix FIFO spectrogram plot

app/plot_app/config.py, app/plot_app/configured_plots.py, app/plot_app/leaflet.py, app/plot_app/pid_analysis.py, app/plot_app/plotted_tables.py, app/plot_app/plotting.py, app/plot_app/statistics_plots.py, app/tornado_handlers/download.py
v6x can easily log the FIFO data of all the IMUs, plotting all of them for comparison is really useful.
Example:
Also fixed the gyro label found in https://github.com/PX4/flight_review/pull/239
=> Plot all available FIFO instances 

README.md
When I first tried to execute the web app, I noticed the log upload wasn't working, since in the README, it wasn't so obvious that it was a necessary step, as it was occluded by the optional user settings description.
Move the Database setup step upwards and make it necessary (hard to miss)
=> README: Make database setup more visible / mandatory

README.md, app/plot_app/templates/header.html, app/tornado_handlers/download.py
When you want to download a parameter file... it can not be directly uploaded into QGC. This givces you the option to download the QGC compatible one. This PR was based off of @farhangnaderi PR here: #264
=> QGC Parameters

app/plot_app/config.py, app/plot_app/configured_plots.py, app/plot_app/static/js/upload.js, app/plot_app/templates/upload.html, app/tornado_handlers/upload.py
=> add upload progress

app/plot_app/config.py, app/plot_app/events.py, app/plot_app/plotted_tables.py, app/requirements.txt
Added in https://github.com/PX4/pyulog/pull/94
Also removes the file caching for the events from the log, as decompressing on the fly is fast enough.
=> messages: use pyulog for events extraction

app/plot_app/configured_plots.py, app/plot_app/vtol_tailsitter.py
I was analysing some logs for a quadtailsitter without control surfaces that i'm developing, and I notice that even though the angle tracking of roll was quite good, the plots for the rates did not make sense
Here the [complete logs](https://review.px4.io/plot_app?log=d21b119d-21dc-45b4-9380-481d8e2cf5cb) for reference 
By looking into the `configured_plots.py` I saw that if the vehicle is a tailsitter angles and rates are reassigned to be plotted in a more consisten way for the instants that drone is flying in fixed wing:
- yaw -> -roll
- roll -> yaw
but this is not applied to the rates setpoint, so the result is that on the rollrate plot , for example , the data shown are:
- in MC 
1. Roll rate
2. Roll rate setpoint
- in FW
1.  Inverse of yaw rate
2. Roll rate setpoint
What I did was …
=> Tailsitter : correct rate setpoint to match rate for tailsitter

app/serve.py, app/tornado_handlers/three_d.py
Fixes these (new) pylint errors:
```
~/work/flight_review/flight_review/app ~/work/flight_review/flight_review
************* Module three_d
tornado_handlers/three_d.py:133:45: E0606: Possibly using variable 'start_timestamp' before assignment (possibly-used-before-assignment)
************* Module serve
serve.py:149:39: E0606: Possibly using variable 'ulog_file' before assignment (possibly-used-before-assignment)
```
=> app: fix pylint 'possible variable use before assignment' error

app/plot_app/configured_plots.py
Remove thrust from altitude graph. Add HDOP, VDOP, and speed accuracy to GPS. Fix vibration instance 3 label.
@dakejahl @dagar
=> Remove thrust from altitude graph. Add HDOP, VDOP, and speed accuracy to GPS. Fix vibration instance 3 label.

app/plot_app/configured_plots.py
This fixes the altitude setpoint display. I still don't know how useful this graph is when you end up with an altitude setpoint at 0m and you are flying at high elevation.
This log looks like it has one setpoint at 0m, setting the scale to start at 0.
=> Fix alt setpoints

.github/workflows/test_docker_build.yml, app/plot_app/config.py
Fixes https://github.com/PX4/flight_review/issues/212
@KarthiAru does that work for you? And for everyone else?
=> Use colorblind friendly palette

app/plot_app/helper.py
Currently any log with a minor corruption will not upload and complain about the log being corrupt. Plotjuggler opens the logs without issue. Allowing string exceptions fixes this.
```
./serve.py --show
/home/alex/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Moving uploaded file to /home/alex/flight_review/app/plot_app/../../data/log_files/10c53e34-3767-493b-ba84-20332f3d225f.ulg
Traceback (most recent call last):
File "/home/alex/flight_review/app/plot_app/helper.py", line 317, …
```
=> Fix uploading of currupt logs

app/plot_app/templates/3d.html, app/tornado_handlers/three_d.py
Regression from 13705a16d9b7c17fe129bf2ef93d8138fd943658. Apparently when I tested it, the previous model was still used due to caching.
=> fix 3D: add 90 deg yaw rotation for plane model

.gitignore, app/README.md, app/config_default.ini, app/plot_app/config.py, app/plot_app/helper.py, app/private_key/dummy_key.pem, app/private_key/private_key.pem, app/requirements.txt, app/tornado_handlers/upload.py
Added logic to handle encrypted logs(.ulge) files
=> Encrypted logs

app/plot_app/configured_plots.py, app/plot_app/helper.py
This PR adds a new graph with ESC RPM if it exists in the log. Along with plotting ESC temperatures if they are present.
I also added the missing background colors for mode changes to other plots.
=> Add ESC RPM and Temperature. Add missing mode background colors
